# ----------------------------------------------
# Adresa APi servera u formi http://imeservera:port/api/v1
# ----------------------------------------------
api.serverurl=http://localhost:33377/api/v1


# ----------------------------------------------
# Adresa KRAN servera u formi http://imeservera:port
# ----------------------------------------------
crane.webServerUrl=http://localhost:33378


# ----------------------------------------------
# Maksimum otvorenih tabova na klijentu. Previse tabova moze da uspori rad
# ---------------------------------------------- 
ui.maxopentabs=5
# ----------------------------------------------


client.itemImagePath=D:/dev/java-ws/repro-market/assets/misc/RM-PRODUKCIJA/ArtikliSlike/
client.clientStoreImagePath=D:/dev/java-ws/repro-market/assets/misc/RM-PRODUKCIJA/RadnjeSlike/


# ----------------------------------------------
# Klijent KRAN instanca
# ----------------------------------------------
client.crane.instance=true
