<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>org.codestudio.client</groupId>
    <artifactId>repromarket-client</artifactId>
    <version>1.0.0</version>
    <name>repromarket-client</name>
    <description>Repromarket client</description>
    <properties>
        <!-- od verzije 16, mozemo da se referenciramo na non-static fields unutar static klasa
             ovo koristim za CSTable custom evente.
             Kada koristim Maven clean package, javlja gresku za non-static, verovatno zato sto 
             ne forsira koriscenje JRE>=16 ... za sada ne znam kako da resim.
             U sustini zamo uradim alt+F5 da bi se rekompajlirao projekat (tada radi) i onda mogu
             da ga pokrenem kroz RUN->
        -->
        <java.version>24</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <javafx-version>24</javafx-version>
        <json-version>20240303</json-version>
        <jasper-version>6.21.2</jasper-version>
        <jasper-build-plugin-version>3.6.1</jasper-build-plugin-version>
        <controlsfx-version>11.2.1</controlsfx-version>
        <ikonli-version>12.3.1</ikonli-version>
        <apache-commons-io-version>2.17.0</apache-commons-io-version>
        <barcode.barbecue.version>1.5-beta1</barcode.barbecue.version>
    </properties>
	<dependencyManagement>
	    <dependencies>
	        <dependency>
	            <groupId>org.kordamp.ikonli</groupId>
	            <artifactId>ikonli-bom</artifactId>
	            <version>${ikonli-version}</version>
	            <type>pom</type>
	            <scope>import</scope>
	        </dependency>
	    </dependencies>
	</dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.code_studio</groupId>
            <artifactId>repromarket-database</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>${javafx-version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx-version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>${javafx-version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-web</artifactId>
            <version>${javafx-version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>${controlsfx-version}</version>
        </dependency>
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>${jasper-version}</version>
        </dependency>
		<dependency>
		    <groupId>net.sf.jasperreports</groupId>
		    <artifactId>jasperreports-functions</artifactId>
		    <version>${jasper-version}</version>
		</dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-javafx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-bootstrapicons-pack</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-materialdesign2-pack</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-fluentui-pack</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-fileicons-pack</artifactId>
        </dependency>
		<dependency>
		    <groupId>org.json</groupId>
		    <artifactId>json</artifactId>
		    <version>${json-version}</version>
		</dependency>
		<dependency>
		    <groupId>commons-io</groupId>
		    <artifactId>commons-io</artifactId>
		    <version>${apache-commons-io-version}</version>
		</dependency>
		<dependency>
		    <groupId>net.sourceforge.barbecue</groupId>
		    <artifactId>barbecue</artifactId>
		    <version>${barcode.barbecue.version}</version>
		</dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-compiler-plugin</artifactId>
			    <configuration>
				    <source>${java.version}</source>
				    <target>${java.version}</target>
			        <enablePreview>false</enablePreview> <!-- enables preview features of the currently selected java, but we must add it in Launch4j also -->
			    </configuration>
			</plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>build-info</id>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
					<execution> <!-- needed for finalName of the jar -->
						<id>repackage</id>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
                </executions>
            </plugin>
            <!-- ovo koristimo za property expansion npr ${api.currentversion} i sl. ->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <!-
                    <delimiters>
                        <delimiter>@</delimiter>
                    </delimiters>
                    ->
                    <useDefaultDelimiters>true</useDefaultDelimiters>
                </configuration>
            </plugin>
            -->
			<plugin>
				<groupId>com.pro-crafting.tools</groupId>
				<artifactId>jasperreports-plugin</artifactId>
				<version>${jasper-build-plugin-version}</version>
				<executions>
					<execution>
						<phase>process-sources</phase>
						<goals>
						    <goal>jasper</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<!-- These are the default configurations: -->
					<compiler>net.sf.jasperreports.engine.design.JRJdtCompiler</compiler>
					<sourceDirectory>src/main/resources/reports</sourceDirectory>
					<outputDirectory>${project.build.directory}/classes/reports</outputDirectory>
					<outputFileExt>.jasper</outputFileExt>
					<xmlValidation>true</xmlValidation>
					<verbose>false</verbose>
					<numberOfThreads>6</numberOfThreads>
					<failOnMissingSourceDirectory>true</failOnMissingSourceDirectory>
					<sourceScanner>org.codehaus.plexus.compiler.util.scan.StaleSourceScanner</sourceScanner>
				</configuration>
			</plugin>
        </plugins>
        <!-- gkljajic, morao sam eksplicitno da dodam ova dva foldera dole
            jedan je za fxml i css fajlove a drugi za .properties. 
         -->
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/java</directory>
                <includes>
                    <include> **/*.*</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>*.jpg</include>
                    <include>*.properties</include>
                    <include>*.ttf</include>
                    <include>*.png</include>
                    <include>*.gif</include>
                    <include>logback.xml</include>
                    <include>reports/*.jasper</include>
                    <include>reports/common/*.jpg</include>
                </includes>
            </resource>
            <!-- properties file outside JAR -->
             <resource>
                <filtering>true</filtering>
                <directory>${project.basedir}</directory>
                <includes>
                    <include>client.properties</include>
                </includes>
                <targetPath>${project.build.directory}</targetPath>
            </resource>
        </resources>
    </build>
</project>
