# -----------------------------------
# BASE
# -----------------------------------
spring.application.name=repromarket-crane
spring.thymeleaf.caching=false

# -----------------------------------
# LOGGING
# -----------------------------------
spring.main.banner-mode=off
spring.main.log-startup-info=false
logging.level.org.springframework.boot.autoconfigure=ERROR

logging.level.root=error
logging.level.org.springframework=error
logging.level.org.springframework.web=error
logging.level.org.hibernate=error

logging.file.name=logs/log.txt
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i

logging.level.org.code_studio=info

#logging.file=logs/app.log
#logging.pattern.file=%d %p %c{1.} [%t] %m%n
#logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n


# -----------------------------------
# WEB SERVER
# -----------------------------------
server.address=localhost
server.port=33378


# -----------------------------------
# DATA SERVER
# API server connected to database, responsible for data fetch
# -----------------------------------
dataserver.address=http://localhost:33377/api/v1


# -----------------------------------
# 1 - Port za TCP server na koji ce da se zakaci UST (predefinisano na UST)
# 2 - Port za TCP client na koji cemo da se zakacimo nasim klijentom (predefinisano na UST)
# -----------------------------------
tcpserver.port=18196
tcpclient.serverport=18197
tcpclient.serveraddress=192.168.9.109
# -----------------------------------
# testiranje
# -----------------------------------
#tcpserver.port=18196
#tcpclient.serverport=18196
#tcpclient.serveraddress=localhost


# -----------------------------------
# ordinal number of ALL telegrams sent to UST
# Increments by 1 every time a telegram is created
# -----------------------------------
tcpclient.ordinalNumber=1


# -----------------------------------
# Auto create crane response messages for palette flow
# Simulates crane responses, debug only!
# -----------------------------------
messageflow.automation.debug=false


# -----------------------------------
# Start app url in browser when
# application init is completed 
# -----------------------------------
applicationreadyevent.startbrowser=false


# -----------------------------------
# How many msecs we wait before
# we send DAYCLOSE event to server
# This is needed because server needs to reply
# and we need to process that reply 
# -----------------------------------
applicationcloseevent.waitMSec=3000


# -----------------------------------
# How many msecs we wait before
# we send TRANSFER event again to server
# when the crane forks are occupied
# and server rejects message with DT status
# -----------------------------------
crane.message.schedule.seconds=10


# -----------------------------------
# set to true when palette arrives
# on 1003, but no palette is defined
# with status 2 that is waiting
# for input to warehouse
# -----------------------------------
crane.palette.iswaiting=false


# -----------------------------------
# if we enable barcode connection
# to COM port and recieve data from it
# based on which we create document
# and palette in format xxxxx.zzyyyzz
# -----------------------------------
crane.barcode.enabled=true


# -----------------------------------
# System name of the COM port
# to which we connect and receive
# barcode data
# -----------------------------------
crane.barcode.systemportname=COM3


# -----------------------------------
# How many seconds we wait until
# we try to open COM port again
# -----------------------------------
crane.barcode.openretrywaitseconds=120