# ----------------------------------------------
# engine parser konfiguracija, moze da pruzrokuje pad sistema ukoliko se nesto menja.
# ----------------------------------------------
cs.engine.parser=MjEwMC0wMS0wMQ==


# ----------------------------------------------
# application version, updated in Jenkins build
# ----------------------------------------------
app.version=0
app.build=0
app.version_datetime=1900-01-01

#----------------------------------------
#Embedded Tomcat bind address & port
#----------------------------------------
jwt.secretKey = jwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecret
security.disable=true

#----------------------------------------
#Embedded Tomcat bind address & port
#----------------------------------------
#server.address=127.0.0.1
server.address=0.0.0.0
server.port=33377

#Velicina page-a koju inicijalno vraca u Pageable ka klijentu
server.pageSize=40

#Exposuje samo rest servise koji imaju annotattion @Repository i @Service
spring.data.rest.detection-strategy=annotated


#----------------------------------------
# CRANE SERVER
#----------------------------------------
craneserver.address=http://localhost:33378


#----------------------------------------
# JMX CONFIG
# TODO: Move JMX config from cmdline to props file
#----------------------------------------
#spring.jmx.enabled=true
#spring.application.admin.enabled
#----------------------------------------
spring.main.banner-mode=off
#spring.main.lazy-initialization=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
server.error.whitelabel.enabled=true

#Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
# ako ovo stavim na false, dobijam greske NO SESSION i COULD NOT INIT PROXY
spring.jpa.open-in-view=true
#----------------------------------------
# LOGGING & DEBUGGING
#----------------------------------------
# ERROR | DEBUG | TRACE | WARN
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot=ERROR
logging.level.org.springframework.web.HttpLogging = TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor = TRACE

logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=ERROR

logging.level.org.code_studio=DEBUG

# logging.level.org.springframework.boot.autoconfigure=ERROR
# logging.level.org.hibernate.type.descriptor=OFF
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
# logging.level.org.hibernate.stat=OFF
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.format_sql=false
spring.output.ansi.enabled=never

#shows request and post params in debug log
spring.mvc.log-request-details=true
#----------------------------------------
# MISC
#----------------------------------------
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
#spring.data.rest.base-path=api
spring.mvc.servlet.path=/api
spring.servlet.multipart.enabled=true
rest.api.version=v1
rest.basepath=${rest.api.version}
springdoc.api-docs.path=${rest.basepath}/api-docs

#----------------------------------------
# mariadb config #
#----------------------------------------
spring.datasource.url = jdbc:mariadb://localhost:33366/rm
spring.datasource.name=repromarket
spring.datasource.username=rm
spring.datasource.password=fsrm
spring.datasource.driver-class-name= org.mariadb.jdbc.Driver
#spring.jpa.database=mysql
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#----------------------------------------
# ROUTER MAPPING
#----------------------------------------
#LOGIN/USER AUTHENTICATION
url.authenticate = ${rest.basepath}/authenticate

#BUSINESS LOGIC SERVICE
url.businessLogicService = ${rest.basepath}/businessLogicService
#----------------------------------------
# APPLICATION VERSION
#----------------------------------------
url.applicationVersion = ${rest.basepath}/applicationVersion
#----------------------------------------

#CLIENT
url.client              = ${rest.basepath}/client
url.clientContact       = ${rest.basepath}/clientContact
url.clientStore         = ${rest.basepath}/clientStore
url.clientPricelist     = ${rest.basepath}/clientPricelist
url.clientLastPaidAmount = ${rest.basepath}/clientLastPaidAmount

#CLIENT GROUP
url.clientGroup         = ${rest.basepath}/clientGroup

#CLIENT CATEGORY
url.clientCategory      = ${rest.basepath}/clientCategory

#CLIENT STORE IMAGE
url.clientStoreImage    = ${rest.basepath}/clientStoreImage

#SUPPLIER
url.supplier            = ${rest.basepath}/supplier

# WAREHOUSE
url.warehouse            = ${rest.basepath}/warehouse
url.itemWarehouse        = ${rest.basepath}/itemWarehouse
url.itemWarehouseBalance = ${rest.basepath}/itemWarehouseBalance
url.itemWarehouseTotals  = ${rest.basepath}/itemWarehouseTotals
url.billOfLadingType     = ${rest.basepath}/billOfLadingType
url.transferOrderType    = ${rest.basepath}/transferOrderType

# DOBANOVCI
url.warehouseTotals      = ${rest.basepath}/warehouseTotals

# ITEM
url.item                 = ${rest.basepath}/item
url.itemType             = ${rest.basepath}/itemType
url.itemStatus           = ${rest.basepath}/itemStatus
url.itemCatalog          = ${rest.basepath}/itemCatalog
url.itemBranch           = ${rest.basepath}/itemBranch
url.itemGroup            = ${rest.basepath}/itemGroup
url.itemSubgroup         = ${rest.basepath}/itemSubgroup
url.itemSet              = ${rest.basepath}/itemSet
url.itemAccessory        = ${rest.basepath}/itemAccessory

# ITEM BALANCE
url.itemBalance          = ${rest.basepath}/itemBalance

# ITEM BARCODE
url.itemBarcode          = ${rest.basepath}/itemBarcode

#LOOKUP
url.currency             = ${rest.basepath}/currency
url.country              = ${rest.basepath}/country

url.deliveryAddress      = ${rest.basepath}/deliveryAddress
url.deliveryAddressType  = ${rest.basepath}/deliveryAddressType
url.paymentType          = ${rest.basepath}/paymentType
url.paymentTerm          = ${rest.basepath}/paymentTerm
url.deliveryType         = ${rest.basepath}/deliveryType
url.saleType             = ${rest.basepath}/saleType
url.vatGroup             = ${rest.basepath}/vatGroup
url.customsGroup         = ${rest.basepath}/customsGroup
url.bankAccount          = ${rest.basepath}/bankAccount
url.cashDesk             = ${rest.basepath}/cashDesk
url.bank                 = ${rest.basepath}/bank
url.measurementUnit      = ${rest.basepath}/measurementUnit
url.packageType          = ${rest.basepath}/packageType
url.applicationLanguage  = ${rest.basepath}/applicationLanguage
url.applicationRole      = ${rest.basepath}/applicationRole
url.applicationUser      = ${rest.basepath}/applicationUser
url.bankStatement        = ${rest.basepath}/bankStatement
url.bankStatementDetail  = ${rest.basepath}/bankStatementDetail
url.clientBankAccount    = ${rest.basepath}/clientBankAccount
url.discount             = ${rest.basepath}/discount
url.discountWithEntity   = ${rest.basepath}/discountWithEntity
url.discountGroup        = ${rest.basepath}/discountGroup
url.brand                = ${rest.basepath}/brand

#SALE-PLANNER
url.salePlanner          = ${rest.basepath}/salePlanner
url.salePlannerType      = ${rest.basepath}/salePlannerType
url.salePlannerReview    = ${rest.basepath}/salePlannerReview
url.salePlannerMonthByDay   = ${rest.basepath}/salePlannerMonthByDay

#SALE-PLANNER-WITH-CLIENT
url.salePlanner_Client   = ${rest.basepath}/salePlanner_Client

#SALE-OFFICER
url.clientSaleOfficerLink = ${rest.basepath}/clientSaleOfficerLink

#BillOfExhange (Menica)
url.billOfExchange      = ${rest.basepath}/billOfExchange

#ClientContract (Ugovor)
url.clientContract      = ${rest.basepath}/clientContract

#Orders
url.orders              = ${rest.basepath}/orders
url.ordersDetail        = ${rest.basepath}/ordersDetail

# ------------------------------------------------------
# INVOICE
# ------------------------------------------------------
url.invoice             = ${rest.basepath}/invoice
url.invoiceDetail       = ${rest.basepath}/invoiceDetail
# ------------------------------------------------------

# ------------------------------------------------------
#Bill of Receipt (Prijemnica)
# ------------------------------------------------------
url.billOfReceipt       = ${rest.basepath}/billOfReceipt
url.billOfReceiptDetail = ${rest.basepath}/billOfReceiptDetail
# ------------------------------------------------------

# ------------------------------------------------------
#PALETTES
# ------------------------------------------------------
url.paletteDocument = ${rest.basepath}/paletteDocument
url.palette         = ${rest.basepath}/palette
url.paletteItem     = ${rest.basepath}/paletteItem
# ------------------------------------------------------

# ------------------------------------------------------
# OFFER
# ------------------------------------------------------
url.offer            = ${rest.basepath}/offer
url.offerDetail      = ${rest.basepath}/offerDetail
# ------------------------------------------------------

# ------------------------------------------------------
#CRANE MANIPULATION
# ------------------------------------------------------
url.craneStorage     = ${rest.basepath}/craneStorage
url.crane            = ${rest.basepath}/crane
url.craneQueue       = ${rest.basepath}/craneQueue

# ------------------------------------------------------
#DIVISION
# ------------------------------------------------------
url.division         = ${rest.basepath}/division

# ------------------------------------------------------
#CLIENT ACCOUNT BALANCE
# ------------------------------------------------------
url.clientAccountBalance = ${rest.basepath}/clientAccountBalance

# ------------------------------------------------------
#TRANSFER ORDER
# ------------------------------------------------------
url.transferOrder = ${rest.basepath}/transferOrder
url.transferOrderDetail = ${rest.basepath}/transferOrderDetail

# ------------------------------------------------------
#CALCULATION
# ------------------------------------------------------
url.calculation = ${rest.basepath}/calculation

# ------------------------------------------------------
#SUPPLIER PRICELIST
# ------------------------------------------------------
url.supplierPricelist     = ${rest.basepath}/supplierPricelist

# ------------------------------------------------------
#INTERNET CATALOG
# ------------------------------------------------------
url.internetCatalog     = ${rest.basepath}/internetCatalog

# ------------------------------------------------------
#INVENTORY LISTING
# ------------------------------------------------------
url.inventoryListing     = ${rest.basepath}/inventoryListing
url.inventoryListingDetail     = ${rest.basepath}/inventoryListingDetail
url.inventoryListingDetailSum     = ${rest.basepath}/inventoryListingDetailSum
# ------------------------------------------------------
# DBINI
# ------------------------------------------------------
url.dbini = ${rest.basepath}/dbini
# ------------------------------------------------------

######### Add path for craneStorageSharedFolder WITH trailing slashes-backslashes #########
#We use setting from server.properties, not this one. craneStorageSharedFolder = D:/dev/java-ws/repro-market/tmp/
### craneStorageFileExtension = PLC

# ------------------------------------------------------
#File import mechanism config
# ------------------------------------------------------
url.fileImporter = ${rest.basepath}/fileImporter
fileImporterLoadFolder=import

# ------------------------------------------------------
#File export mechanism config
# ------------------------------------------------------
url.fileExporter = ${rest.basepath}/fileExporter
fileExporterSaveFolder = export
url.fileBankStatement  = ${rest.basepath}/fileBankStatement

# ------------------------------------------------------
# CLIENT APP LANGUAGE #
# ------------------------------------------------------
#url.menus.lang_en = en
#url.menus.lang_rs = rs

# ------------------------------------------------------
# SALE OFFICER ROLE IDs
# ------------------------------------------------------
app.saleOfficerRoleIds = 10,11,12


# ------------------------------------------------------
# ENUMERATOR ROLE IDs, used is POPIS - inventory listing
# ------------------------------------------------------
app.enumeratorRoleIds = 24

#----------------------------------------
# CONFIGURATION EXPOSED TO THE USER
# AVAILABLE IN CLIENT.PROPERTIES FILE
# THAT RESIDES NEXT TO JAR/EXE FILE
# We need to copy it with maven build
#----------------------------------------
spring.config.import=file:server.properties

#----------------------------------------
# SERVER ONLY CONFIG PARAMS
#----------------------------------------
server.itemImagePath=D:/dev/java-ws/repro-market/assets/misc/RM-PRODUKCIJA/ArtikliSlike/
server.bankStatementWatchFolder=import/bank_statement

