#add path for craneStorageSharedFolder WITH trailing slashes-backslashes
craneStorageSharedFolder  = D:/dev/java-ws/repro-market/tmp/
craneStorageFileExtension = plc

#Possible values: SEQUENTIAL|ALTERNATE
craneFillOrdinal = SEQUENTIAL

#Possible values: ROW_START_TO_MIDDLE|ROW_MIDDLE_TO_END
craneFillOrder   = ROW_START_TO_MIDDLE

#defined maximum IDs for row/shelf/vertical
maxShelf         = 204
maxVertical      = 7
crane1StartRow   = 1
crane1EndRow     = 4
crane2StartRow   = 5
crane2EndRow     = 8


# ----------------------------------------------
# Konfiguracija lokalnih foldera na serveru, bez poslednjeg slash-a
# ----------------------------------------------\
server.itemImagePath=D:/dev/java-ws/repro-market/assets/misc/RM-PRODUKCIJA/ArtikliSlike/
