# ----------------------------------------------
# engine parser konfiguracija, moze da pruzrokuje pad sistema ukoliko se nesto menja.
# ----------------------------------------------
cs.engine.parser=MjEwMC0wMS0wMQ==


# ----------------------------------------------
# application version, updated in Jenkins build
# ----------------------------------------------
app.version= 


# ----------------------------------------------
# Adresa APi servera u formi http://imeservera:port/api/v1
# ----------------------------------------------
api.serverurl=http://localhost:33377/api/v1


# ----------------------------------------------
# Adresa KRAN servera u formi http://imeservera:port
# ----------------------------------------------
crane.webServerUrl=http://localhost:33378


#----------------------------------------
#Embedded Tomcat bind address & port
#----------------------------------------
spring.profiles.active=local


#----------------------------------------
# Spring related config
#----------------------------------------
spring.main.web-application-type=none
spring.main.banner-mode=off
spring.main.log-startup-info=false

# not used anymore
# We use maven buldproperties and set app title
# in stageinitializer
# spring.application.ui.title=TEST


#----------------------------------------
# LOGGING & DEBUGGING
#----------------------------------------
logging.level.root=ERROR
logging.level.org.springframework=ERROR
#logging.level.org.springframework.web.client.RestTemplate=ERROR
logging.level.org.apache.http=ERROR
logging.level.httpclient.wire=ERROR
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.code_studio=DEBUG

#logging.file=logs/app.log
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
#----------------------------------------
#Client UI config
#----------------------------------------
ui.language=sr

# ----------------------------------------------
# Maksimum otvorenih tabova na klijentu. Previse tabova moze da uspori rad
# ---------------------------------------------- 
ui.maxopentabs=5
# ----------------------------------------------


# If TRUE, when user types anything while the table is in focus, search box captures letters and on ENTER performs the search
# If FALSE, user must focus search box to type search phrase and search the table.
ui.table.enhancedsearch=true

#Various debug features which are not aailable in user mode
debugmode=true

#Forces maxWidth and maxHeight of main window
ui.mainwindow.forceMaxSize=true
ui.mainwindow.maxWidth=1024
ui.mainwindow.maxHeight=740
ui.dialog.resizable=false
security.disable=true

#Automatically select first row in all tables (immediately after populating data in them) 
#if there is at least one row in the table
ui.table.autoselectfirstrow=true

#Automatically maximize initial app screen, immediately after user logs in.
ui.mainwindow.maximizeonstart=false
ui.mainwindow.resizable=true

applicationlog.numberoflinestoread = 1000

#----------------------------------------
# API, overriden in client.properties
#----------------------------------------
api.currentversion=v1
url.user=${api.version}/${us}
#### api.serverurl=http://localhost:33377/api/v1 ### Defined in Client.properties 


#----------------------------------------
# CONFIGURATION EXPOSED TO THE USER
# AVAILABLE IN CLIENT.PROPERTIES FILE
# THAT RESIDES NEXT TO JAR/EXE FILE
# We need to copy it with maven build
# important: we use custom props loader
# so this one never works
# we included manually this file 
# in Common.props load
#----------------------------------------
#spring.config.import=file:client.properties


#----------------------------------------
# CLIENT ONLY CONFIG PARAMS
#----------------------------------------
client.itemImagePath=D:/dev/java-ws/repro-market/assets/misc/RM-PRODUKCIJA/ArtikliSlike/
client.clientStoreImagePath=D:/dev/java-ws/repro-market/assets/misc/RM-PRODUKCIJA/RadnjeSlike/

### Applies for CSPhotoView component ###
# Controls whether client app will show an error if image for an item is defined, but we cannot find the path in the local filesystem
client.showMissingItemImageError=false
# Whether we log the error for the above
client.logMissingItemImageError=false

#----------------------------------------
# IS THIS INSTANCE THAT RUNS IN DOBANOVCI?
#----------------------------------------
client.crane.instance=false


#----------------------------------------
# MISC
#----------------------------------------
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false