package org.code_studio.database;
// Generated Dec 3, 2021, 12:45:03 PM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * ApplicationRole generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "APPLICATION_ROLE", schema = "PUBLIC", catalog = "RM")
public class ApplicationRole implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;

	public ApplicationRole() {}

	public ApplicationRole(String name, String description) {
		this.name = name;
		this.description = description;
	}
	
	/**
	 * DEBUG ONLY
	 */
	public ApplicationRole(Integer id) {
		this.id = 1;
		this.name = "Administrator";
		this.description = "DEBUG ONLY !!!";
 	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
