package org.code_studio.database;
// Generated Dec 3, 2021, 12:06:32 PM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * ApplicationLanguage generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "APPLICATION_LANGUAGE", schema = "PUBLIC", catalog = "RM")
public class ApplicationLanguage implements java.io.Serializable {

	private Integer id;
	private String code;
	private String name;
	private String description;

	public ApplicationLanguage() {
	}

	public ApplicationLanguage(String code) {
		this.code = code;
	}

	public ApplicationLanguage(String code, String name, String description) {
		this.code = code;
		this.name = name;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
