package org.code_studio.database;
// Generated Dec 3, 2021, 12:45:03 PM by Hibernate Tools 4.3.5.Final

import java.time.LocalDateTime;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * ApplicationUser generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "APPLICATION_USER", schema = "PUBLIC", catalog = "RM")
public class ApplicationUser implements java.io.Serializable {

	private Integer id;
	private String username;
	private String name;
	private String password;
	private Integer roleId;
	private LocalDateTime lastLoginDate;
	private ApplicationRole applicationRole;
	
	@JsonBackReference(value="Back:salePlannerType->salePlanner")
	private List <SalePlanner> salePlanner;
	
	@JsonBackReference(value="Back:ApplicationUser->ClientSaleOfficerLink")
	private List <ClientSaleOfficerLink> clientSaleOfficerLink;

	public ApplicationUser() {}

	public ApplicationUser(String username, String name, String password, Integer roleId, LocalDateTime lastLoginDate) {
		this.username = username;
		this.name = name;
		this.password = password;
		this.roleId = roleId;
		this.lastLoginDate = lastLoginDate;
	}
	
	/**
	 * USed when no user is logged, just for debug, there must be user logged in all the time
	 */
	public ApplicationUser(Integer id) {
		this.id = id;
		this.username = "Bane";
		this.name = "Milenković Slobodan";
		this.password = "";
		this.roleId = 1;
		this.lastLoginDate = LocalDateTime.now();
		this.applicationRole = new ApplicationRole();
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USERNAME", length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PASSWORD", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ROLE_ID")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "LAST_LOGIN_DATE")
	public LocalDateTime getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(LocalDateTime lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "saleOfficer")
	public List <SalePlanner> getSalePlanner() {
		return this.salePlanner;
	}

	public void setSalePlanner( List <SalePlanner> salePlanner) {
		this.salePlanner = salePlanner;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applicationUser", cascade = CascadeType.ALL)
	//@OneToOne(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
    /*@JoinTable(
        name = "CLIENT_SALE_OFFICER_LINK", 
        joinColumns = { @JoinColumn(name = "SALE_OFFICER_ID") }, 
        inverseJoinColumns = { @JoinColumn(name = "ID") }
    )*/
	public List <ClientSaleOfficerLink> getClientSaleOfficerLink() {
		return this.clientSaleOfficerLink;
	}

	public void setClientSaleOfficerLink(List <ClientSaleOfficerLink> clientSaleOfficerLink) {
		this.clientSaleOfficerLink = clientSaleOfficerLink;
	}

	@OneToOne
	@JoinColumn(name = "ROLE_ID", updatable = false, insertable = false)
	public ApplicationRole getApplicationRole() {
		return applicationRole;
	}

	public void setApplicationRole(ApplicationRole applicationRole) {
		this.applicationRole = applicationRole;
	}
	
	@Transient
	public String getRoleName() {
		return applicationRole != null ? applicationRole.getName() : "";
	}

	@Transient
	public ApplicationUserName getApplicationUserName() {
		return new ApplicationUserName(id, username, name, roleId);
	}

}
