package org.code_studio.database;
// Generated Dec 2, 2021, 3:36:46 PM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * BankAccount generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "BANK_ACCOUNT", schema = "PUBLIC", catalog = "RM")
public class BankAccount implements java.io.Serializable {

	private Integer id;
	private String accountNumber;
	private Bank bank;
	private String iban;
	private String description;

	public BankAccount() {
	}

	public BankAccount(String accountNumber, Bank bank, String iban, String description) {
		this.accountNumber = accountNumber;
		this.bank = bank;
		this.iban = iban;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ACCOUNT_NUMBER", length = 100)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@OneToOne
	public Bank getBank() {
		return bank;
	}

	public void setBank(Bank bank) {
		this.bank = bank;
	}

	@Column(name = "IBAN", length = 100)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Transient
	public String getBankName() {
		return bank != null
			? bank.getName()
			: "";
	}

}
