package org.code_studio.database;
// Generated Nov 15, 2022, 5:26:23 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Crane generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "CRANE", schema = "PUBLIC", catalog = "RM")
public class Crane implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer isActive;
	private Integer rowStart;
	private Integer rowEnd;
	private Integer shelfCnt;
	private Integer verticalCnt;
	private String description;

	public Crane() {
	}

	public Crane(String name, Integer isActive, Integer rowStart, Integer rowEnd, Integer shelfCnt, Integer verticalCnt,
			String description) {
		this.name = name;
		this.isActive = isActive;
		this.rowStart = rowStart;
		this.rowEnd = rowEnd;
		this.shelfCnt = shelfCnt;
		this.verticalCnt = verticalCnt;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Column(name = "ROW_START")
	public Integer getRowStart() {
		return this.rowStart;
	}

	public void setRowStart(Integer rowStart) {
		this.rowStart = rowStart;
	}

	@Column(name = "ROW_END")
	public Integer getRowEnd() {
		return this.rowEnd;
	}

	public void setRowEnd(Integer rowEnd) {
		this.rowEnd = rowEnd;
	}

	@Column(name = "SHELF_CNT")
	public Integer getShelfCnt() {
		return this.shelfCnt;
	}

	public void setShelfCnt(Integer shelfCnt) {
		this.shelfCnt = shelfCnt;
	}

	@Column(name = "VERTICAL_CNT")
	public Integer getVerticalCnt() {
		return this.verticalCnt;
	}

	public void setVerticalCnt(Integer verticalCnt) {
		this.verticalCnt = verticalCnt;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
